# what is function Transformer in Machine Learning


#the function transformer is a tool in scikit-learn , a popular Python Library for machine learning , that allows you to apply a specific function to the input data. The function Transformer can be useful for performing custom transformation of input data in a machine learning pipeline

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [ ]:
# create a data set
x = np.array([[1,2],[3,4]])

# define the transformation function
log_transform = FunctionTransformer(np.log1p)

# apply the transformation to the data set
x_transformed = log_transform.transform(x)

# view the transformed data
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [ ]:
# Practical use case

#  1. custom feature Engineering
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
x= np.array([[1,2],[3,4]])

# define a custom feature engineering function
def squ(x):
  return np.hstack((x , x**2))

# create a function transformer to apply the custom function
custom_transformer = FunctionTransformer(squ)


# apply the transformer to the input file
x_transformed = custom_transformer.transform(x)

print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [ ]:
# create a dataset
x = np.array([[1,2],[3,4]])

# define a custom scaling function
def my_scaling(x):
  return x/ np.max(x)

# create a function Transformer to apply the custom function
custom_transformer = FunctionTransformer(my_scaling)

# apply the transformer to the input data
x_transformed = custom_transformer.transform(x)


# view the transformed data
x_transformed

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [ ]:
# create a dataset
x = np.array([[1,2],[3,np.nan]])

# define a custom cleaning function
def my_cleaning(x):
  x[np.isnan(x)] = 0
  return x

# create a functionTransformer to apply the custom function
custom_transformer = FunctionTransformer(my_cleaning)

# apply the transformer to the input data
x_transformed = custom_transformer.transform(x)

# view the transformed data
x_transformed

array([[1., 2.],
       [3., 0.]])

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/placement.csv')
df.head()

,cgpa,resume_score,placed
0,8.14,6.52,1
1,6.17,5.17,0
2,8.27,8.86,1
3,6.88,7.27,1
4,7.52,7.30,1


In [ ]:
x = df.drop(columns =['placed'])
y = df['placed']

In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
log_transform = FunctionTransformer(np.log1p)

In [ ]:
# apply the transformation to the dataset
x_transformed = log_transform.transform(x)

In [ ]:
x_transformed

,cgpa,resume_score
0,2.212660,2.017566
1,1.969906,1.819699
2,2.226783,2.288486
3,2.064328,2.112635
4,2.142416,2.116256
...,...,...
95,1.991976,1.998774
96,2.222459,2.170196
97,2.034706,2.172476
98,2.212660,1.891605


In [ ]:
a = pd.read_csv('/content/insurance.csv')

In [ ]:
a.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
a['sex'] = lb.fit_transform(a['sex'])
a['smoker'] = lb.fit_transform(a['smoker'])
a['region'] = lb.fit_transform(a['region'])

In [ ]:
log_transform = FunctionTransformer(np.log1p)

In [ ]:
x_transformed = log_transform.transform(a)

In [ ]:
x_transformed

,age,sex,bmi,children,smoker,region,charges
0,2.995732,0.000000,3.363842,0.000000,0.693147,1.386294,9.734236
1,2.944439,0.693147,3.548755,0.693147,0.000000,1.098612,7.453882
2,3.367296,0.693147,3.526361,1.386294,0.000000,1.098612,8.400763
3,3.526361,0.693147,3.165686,0.000000,0.000000,0.693147,9.998137
4,3.496508,0.693147,3.397189,0.000000,0.000000,0.693147,8.260455
...,...,...,...,...,...,...,...
1333,3.931826,0.693147,3.464798,1.386294,0.000000,0.693147,9.268755
1334,2.944439,0.000000,3.494080,0.000000,0.000000,0.000000,7.699381
1335,2.944439,0.000000,3.633631,0.000000,0.000000,1.098612,7.396847
1336,3.091042,0.000000,3.288402,0.000000,0.000000,1.386294,7.605365
